# https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#actuator-changes
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      base-path: "/actuator"
      exposure: # https://docs.spring.io/spring-boot/docs/3.0.4/reference/html/actuator.html#actuator.endpoints.exposing
        include: "health,info,startup,env,mappings,metrics" # "*"
        exclude: "beans"
    jmx:
      base-path: "/actuator"
      exposure: # https://docs.spring.io/spring-boot/docs/3.0.4/reference/html/actuator.html#actuator.endpoints.exposing
        include: "health,info,startup,env,mappings,metrics" # "*"
        exclude: "beans"           
  endpoint:
    health:
      show-details: always
      show-components: always
      enabled: true
      status:
        http-mapping:
          down: 503
          fatal: 503
          out-of-service: 503
      group:
        readiness:
          include: "readinessState"
        liveness:
          include: "livenessState"
        #startup:
          #include: readinessProbe
    startup: # https://docs.spring.io/spring-boot/docs/3.0.4/reference/html/actuator.html#actuator.endpoints.kubernetes-probes
      enabled: true 
    probes:
        enabled: true      
    info:
      enabled: true
    env:
      enabled: true
    mappings:
      enabled: true            
  server:
    port: 8081