apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-service
spec:
  selector:
      matchLabels:
        app: hello-service
  replicas: 1
  template:
      metadata:
        labels:
            app: hello-service
      spec:
        containers:
        - name: hello-service
          image: ${CONTAINER_REGISTRY}.azurecr.io/${REPOSITORY}/hello-service:${IMAGE_TAG}
          imagePullPolicy: Always
          # By default, the /actuator/httpexchanges endpoint is disabled in Spring Boot 3. To enable it, you will need to add the following to your application.properties file
          livenessProbe: # https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints.kubernetes-probes
            initialDelaySeconds: 5
            timeoutSeconds: 15
            failureThreshold: 5
            successThreshold: 1
            periodSeconds: 15
            httpGet:
              # https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
              # management.endpoints.web.base-path=/actuator
              path: /actuator/health/liveness
              port: 8081
              scheme: HTTP
          readinessProbe:
            initialDelaySeconds: 5
            timeoutSeconds: 15
            failureThreshold: 5
            successThreshold: 1
            periodSeconds: 15
            httpGet:
              path: "/actuator/health/readiness"
              port: 8081           

          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
          - containerPort: 8080
            name: server
          - containerPort: 8081
            name: management

          volumeMounts:
          - name: application-config 
            mountPath: "/tmp/app" 
            readOnly: true

          # https://kubernetes.io/docs/concepts/configuration/configmap/
          # https://developers.redhat.com/blog/2017/10/03/configuring-spring-boot-kubernetes-configmap#setup

        volumes:
        - name: application-config
          configMap:
            name: spring-app-config 
            items:
            - key:  log4j2.yaml  
              path:  log4j2.yaml               
        